project:
  type: book
  output-dir: docs
book:
  title: "Basic R Course"
  author: "Sara Baart, David Nieuwenhuijse, Sten Willemsen, Sanne Hoeks, Elrozy Andrinopoulou, Elizabeth Ribble, Karl Brand"
  date: "04-06-2024"
  chapters:
    - index.qmd
    - part: 1-1_Introduction.qmd
      chapters: 
        - 1-2_Working_with_R.qmd
        - 1-3_Working_with_R_practical.qmd
        - 1-4_Working_with_R_answers.qmd
    - part: 1-5_Common_Objects.qmd
      chapters: 
        - 1-6_Common_Objects_practical.qmd
        - 1-7_Common_Objects_answers.qmd
    - part: 1-8_Indexing_Subsetting.qmd
      chapters: 
        - 1-9_Indexing_Subsetting_practical.qmd
        - 1-10_Indexing_Subsetting_answers.qmd
    - part: 2-1_Datacleaning.qmd
      chapters:
        - 2-2_Datacleaning_practical.qmd
        - 2-3_Datacleaning_answers.qmd
    - part: 2-4_Analysis.qmd
      chapters:
        - 2-5_Analysis_practical.qmd
        - 2-6_Analysis_answers.qmd
    - part: 2-7_Basic_plotting.qmd
      chapters:
        - 2-8_Basic_plotting_practical.qmd
        - 2-9_Basic_plotting_answers.qmd
    - part: 2-10_ggplot2.qmd
      chapters:
        - 2-11_ggplot2_practical.qmd
        - 2-12_ggplot2_answers.qmd
    - part: 3-1_Functions1.qmd
      chapters:
        - 3-2_Functions1_practical.qmd
        - 3-3_Functions1_answers.qmd
    - part: 3-4_Functions2.qmd
      chapters:
        - 3-5_Functions2_practical.qmd
        - 3-6_Functions2_answers.qmd
    - part: 4-1_represearch.qmd
      chapters:
        - 4-2_basic_markdown.qmd
        - 4-3_codeblocks.qmd
        - 4-4_basic_markdown_practicals_questions.qmd
        - 4-5_basic_markdown_practicals_hints.qmd
        - 4-6_basic_markdown_practicals_solution.qmd
        - 4-7_shiny.qmd
        - 4-8_shiny_practicals_questions.qmd
    - part: 4-9_looseends.qmd
      chapters:
        - 4-10_tidyverse.qmd
  repo-url: https://github.com/dnieuw/BasicRcourseEMC
  repo-actions: [edit]
  downloads: [pdf]

format:
  html:
    theme:
      light: cosmo
      dark: solar
  pdf:
    documentclass: scrreprt

editor: visual

number-depth: 2