project:
  type: book
  output-dir: docs
book:
  title: "Basic R Course"
  author: "Sara Baart, David Nieuwenhuijse, Sten Willemsen, Sanne Hoeks, Elrozy Andrinopoulou, Elizabeth Ribble, Karl Brand"
  date: "08-11-2023"
  chapters:
    - index.qmd
    - part: 1-1_Importing_Saving.qmd
      chapters: 
        - 1-2_Importing_Saving_practical.qmd
    - part: 1-3_Common_Objects.qmd
      chapters: 
        - 1-4_Common_Objects_practical.qmd
    - part: 1-5_Indexing_Subsetting.qmd
      chapters: 
        - 1-6_Indexing_Subsetting_practical.qmd
    - part: 2-1_Datacleaning.qmd
      chapters:
        - 2-2_Datacleaning_practical.qmd
        - 2-3_Datacleaning_answers.qmd
    - part: 2-4_Analysis.qmd
      chapters:
        - 2-5_Analysis_practical.qmd
        - 2-6_Analysis_answers.qmd
    - part: 2-7_basic_plotting_intro.qmd
      chapters:
        - 2-8_basic_plotting.qmd
    - part: 2-9_basic_plotting_practicals_intro.qmd
      chapters: 
        - 2-10_basic_plotting_practicals_questions.qmd
        - 2-11_basic_plotting_practicals_answers.qmd
    - part: 2-12_ggplot2_intro.qmd
      chapters:
        - 2-13_ggplot2.qmd
    - part: 2-14_ggplot2_practicals_intro.qmd
      chapters:
        - 2-15_ggplot2_practicals_questions.qmd
        - 2-16_ggplot2_practicals_answers.qmd
    - part: 3-1_functions_intro.qmd
      chapters:
        - 3-2_functions_examples.qmd
        - 3-3_functions_arguments.qmd
        - 3-4_functions_custom.qmd
        - 3-5_functions_conditional.qmd
        - 3-6_functions_terminating.qmd
        - 3-7_functions_looping.qmd
        - 3-8_functions_apply.qmd
    - part: 3-9_functions_practicals1_intro.qmd
      chapters:
        - 3-10_functions_practicals_questions.qmd
        - 3-11_functions_practicals_answers.qmd
    - part: 4-1_represearch.qmd
      chapters:
        - 4-2_basic_markdown.qmd
        - 4-3_codeblocks.qmd
        - 4-4_basic_markdown_practicals_questions.qmd
        - 4-5_shiny.qmd
        - 4-6_shiny_practicals_questions.qmd
    - part: 4-7_looseends.qmd
      chapters:
        - 4-8_tidyverse.qmd
  repo-url: https://github.com/dnieuw/BasicRcourseEMC
  repo-actions: [edit]
  downloads: [pdf]

format:
  html:
    theme:
      light: cosmo
      dark: solar
  pdf:
    documentclass: scrreprt

editor: visual

number-depth: 2